In [2]:
import numpy as np

In [4]:
# z1: Одномерный массив заполненный 0 длиной l
l = 5
z1 = np.zeros(l)

# z2: Двумерный массив заполненный 0 размером width x height
width = 2
height = 3
z2 = np.zeros([width,height], dtype = np.int16)

print(z1)
print(z2)

[ 0.  0.  0.  0.  0.]
[[0 0 0]
 [0 0 0]]


In [13]:
o1 = np.ones(5)
o2 = np.ones([2,2,3], dtype = np.int16)

print(o1)
print(o2)

[ 1.  1.  1.  1.  1.]
[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


In [14]:
a1 = np.arange(2, 20, 2)
print(a1)

[ 2  4  6  8 10 12 14 16 18]


In [16]:
a1 = np.linspace(0,2,9)
print(a1)

array([ 0.        ,  0.22222222,  0.44444444,  0.66666667,  0.88888889,
        1.11111111,  1.33333333,  1.55555556,  1.77777778,  2.        ])

In [19]:
a1 = np.full((2, 2), 7)
print(a1)

[[[7 7]
  [7 7]]

 [[7 7]
  [7 7]]]


In [20]:
a1 = np.eye(2)
print(a1)

array([[ 1.,  0.],
       [ 0.,  1.]])

In [34]:
a1 = np.random.random((2,3))
print(a1)

[[ 0.21194757  0.20481631  0.36710736]
 [ 0.37430007  0.24049843  0.71003846]]


In [44]:
# Пустой массив?!
np.empty(10)

array([ 0.89078891,  0.26396881,  0.30721582,  0.99009531,  0.45867712,
        0.30558651,  0.57776508,  0.8074069 ,  0.54554035,  0.62287709])

In [60]:
a1 = np.random.random((2,2))
print("Original array \n",a1)
t1 = a1.transpose()
print("Transposed array \n",t1)

Original array 
 [[ 0.85708377  0.5391729 ]
 [ 0.09966986  0.34518977]]
Transposed array 
 [[ 0.85708377  0.09966986]
 [ 0.5391729   0.34518977]]
